<?php
$QUESTIONS = [
  1 => ['Quando algo bom acontece, qual voz sussurra primeiro na tua cabeça?', [
    'A' => '“Vai acabar.”',
    'B' => '“Não conte pra ninguém.”',
    'C' => '“Você não merece.”',
    'D' => '“Melhor não se apegar.”',
    'E' => '“Você não vai sustentar isso.”',
    'F' => '“Era melhor nem ter vindo.”',
    'G' => '“Vão rir de você.”',
    'H' => '“Alguém já fez melhor.”',
  ]],
  2 => ['O que você finge que superou, mas ainda aperta quando encosta?', [
    'A' => 'Ser deixado.',
    'B' => 'Ser ignorado.',
    'C' => 'Ser desobedecido.',
    'D' => 'Ser desacreditado.',
    'E' => 'Ser freado.',
    'F' => 'Ser podado.',
    'G' => 'Ser apagado.',
    'H' => 'Ser trocado.',
  ]],
  3 => ['Quando chora, você:', [
    'A' => 'Se esconde.',
    'B' => 'Ri antes.',
    'C' => 'Fica com raiva por estar chorando.',
    'D' => 'Se cala por completo.',
    'E' => 'Pensa que é ridículo sentir isso.',
    'F' => 'Troca de assunto com a própria cabeça.',
    'G' => 'Se julga.',
    'H' => 'Imagina alguém não se importando.',
  ]],
  4 => ['Quando sente alegria, seu corpo faz o quê?', [
    'A' => 'Treme.',
    'B' => 'Congela.',
    'C' => 'Sente culpa.',
    'D' => 'Busca onde está o erro.',
    'E' => 'Fica alerta.',
    'F' => 'Se sabota logo em seguida.',
    'G' => 'Se envergonha.',
    'H' => 'Compara com o outro.',
  ]],
  5 => ['Você disfarça melhor:', [
    'A' => 'O prazer.',
    'B' => 'A dor.',
    'C' => 'A raiva.',
    'D' => 'O medo.',
    'E' => 'O desejo.',
    'F' => 'A dúvida.',
    'G' => 'A vaidade.',
    'H' => 'A necessidade de ser o único.',
  ]],
  6 => ['Qual parte de você é mais bem domesticada?', [
    'A' => 'A que ri alto.',
    'B' => 'A que chora por nada.',
    'C' => 'A que bate porta.',
    'D' => 'A que treme de medo.',
    'E' => 'A que quer o impossível.',
    'F' => 'A que pergunta demais.',
    'G' => 'A que se admira.',
    'H' => 'A que exige exclusividade.',
  ]],
  7 => ['Qual dessas frases te envenenaram cedo demais?', [
    'A' => '“Para de fazer festa.”',
    'B' => '“Não foi nada.”',
    'C' => '“Fale baixo.”',
    'D' => '“Engole esse choro.”',
    'E' => '“Você não tem juízo.”',
    'F' => '“Você pergunta demais.”',
    'G' => '“Você se acha.”',
    'H' => '“Você é substituível.”',
  ]],
  8 => ['Qual dessas máscaras você usa com perfeição?', [
    'A' => 'A leve.',
    'B' => 'A produtiva.',
    'C' => 'A calma.',
    'D' => 'A racional.',
    'E' => 'A confiante.',
    'F' => 'A cínica.',
    'G' => 'A humilde.',
    'H' => 'A desapegada.',
  ]],
  9 => ['Quando está feliz, você tem medo de:', [
    'A' => 'Contar e perder.',
    'B' => 'Não saber lidar depois.',
    'C' => 'Que estraguem tudo.',
    'D' => 'Que descubram sua insegurança.',
    'E' => 'Que vire uma ilusão.',
    'F' => 'Que tirem isso de você.',
    'G' => 'Que te vejam ridículo.',
    'H' => 'Que outro receba mais.',
  ]],
  10 => ['Quando alguém te ignora, o que morde por dentro?', [
    'A' => 'A vontade de sumir.',
    'B' => 'A certeza de que você incomoda.',
    'C' => 'A fúria disfarçada.',
    'D' => 'O pavor de ser invisível.',
    'E' => 'O desejo de nunca mais tentar.',
    'F' => 'A sensação de estar preso.',
    'G' => 'A pergunta: “o que fiz de errado?”',
    'H' => 'O desejo de ser mais especial do que ele.',
  ]],
  11 => ['Qual dessas frases você diria só em pensamento?', [
    'A' => '“Eu queria ser feliz sem medo.”',
    'B' => '“Eu tô triste e ninguém nota.”',
    'C' => '“Eu tô prestes a explodir.”',
    'D' => '“Eu queria poder falhar.”',
    'E' => '“Eu queria fugir e recomeçar.”',
    'F' => '“Eu sinto que morro um pouco todo dia.”',
    'G' => '“Eu mereço mais do que isso.”',
    'H' => '“Eu queria ser insubstituível.”',
  ]],
  12 => ['Onde mora teu monstro?', [
    'A' => 'No sorriso contido.',
    'B' => 'Nos olhos secos.',
    'C' => 'No maxilar tenso.',
    'D' => 'No silêncio fingido.',
    'E' => 'Na gaveta de projetos não feitos.',
    'F' => 'Nos livros que você leu e não viveu.',
    'G' => 'Na roupa que você escolhe pra agradar.',
    'H' => 'No scroll infinito pra ver se o outro ainda te quer.',
  ]],
  13 => ['Quando alguém te reconhece, você:', [
    'A' => 'Ri e desconversa.',
    'B' => 'Acha que é exagero.',
    'C' => 'Fica desconfiado.',
    'D' => 'Duvida da intenção.',
    'E' => 'Pensa “por quanto tempo?”',
    'F' => 'Pensa que enganou bem.',
    'G' => 'Fica constrangido.',
    'H' => 'Quer saber se falou isso pra mais alguém.',
  ]],
  14 => ['Qual desses infernos você constrói com maestria?', [
    'A' => 'O do “quase fui feliz.”',
    'B' => 'O do “nunca tive tempo pra mim.”',
    'C' => 'O do “engoli sapos demais.”',
    'D' => 'O do “tive que ser forte cedo demais.”',
    'E' => 'O do “ninguém acreditava em mim.”',
    'F' => 'O do “precisei virar adulto muito rápido.”',
    'G' => 'O do “ninguém me viu de verdade.”',
    'H' => 'O do “nunca fui escolhido de verdade.”',
  ]],
  15 => ['O que você mais teme que descubram sobre você?', [
    'A' => 'Que você quer brilhar.',
    'B' => 'Que você tá sempre à beira do colapso.',
    'C' => 'Que você odeia sorrir fingindo.',
    'D' => 'Que você ainda sonha com o que desistiu.',
    'E' => 'Que você não é tão estável assim.',
    'F' => 'Que você ainda busca sentido em tudo.',
    'G' => 'Que você queria ser aplaudido.',
    'H' => 'Que você morre de medo de ser esquecido.',
  ]],
  16 => ['Qual sombra você mais finge não ter?', [
    'A' => 'A que se sabota.',
    'B' => 'A que paralisa.',
    'C' => 'A que odeia sorrir.',
    'D' => 'A que deseja morrer por um segundo.',
    'E' => 'A que sente prazer em arriscar tudo.',
    'F' => 'A que mente pra sobreviver.',
    'G' => 'A que quer aplauso.',
    'H' => 'A que quer ser dono do outro.',
  ]],
];
